config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LogoutView

urlpatterns = [
    #path('admin/', admin.site.urls),  # 管理画面を有効化する場合
    path('equipment/', include('equipment.urls')),  # equipment アプリの URL
    path('order_history/', include('order.urls')),  # orderアプリの URL
    path('', include('users.urls')),
    path('logout/', LogoutView.as_view(), name='logout'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

equipment/urls.py
from django.urls import path
from .views import EquipListView,EquipCreateView,EquipDetailView,EquipUpdateView,EquipDeleteView

app_name = 'equipment'
urlpatterns = [
    path('', EquipListView.as_view(), name='list'),
    path('add/', EquipCreateView.as_view(), name='add'),
    path('<int:pk>', EquipDetailView.as_view(), name='detail'),
    path('<int:pk>/edit/', EquipUpdateView.as_view(), name='edit'),
    path('<int:pk>/delete', EquipDeleteView.as_view(), name='delete'),
]

order/urls.py
from django.urls import path
from .views import OrderListView

app_name = 'order'
urlpatterns = [
    path('', OrderListView.as_view(), name='history'),
]

equipment/models.py
from django.db import models
from django.conf import settings

class Equipment(models.Model):
  class Meta:
    db_table = 'equip'

  equip_name = models.CharField(max_length=50,null=False)
  category = models.CharField(max_length=50,null=False)
  place = models.CharField(max_length=50,null=False)
  condition  = models.CharField(max_length=50,null=False)
  stock = models.PositiveIntegerField(null=False)
  text = models.TextField(null=False)
  image = models.ImageField(upload_to='images/', blank=False, null=False)
  created_at = models.DateTimeField(auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True)
  user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,null=True)

class StockChange(models.Model):
    class Meta:
      db_table = 'stockchange'

    equip = models.ForeignKey(Equipment, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    changed_date = models.DateTimeField(auto_now_add=True)
    previous_stock = models.PositiveIntegerField()
    new_stock = models.PositiveIntegerField()

equipment/forms.py
from .models import Equipment
from django import forms

class EquipForm(forms.ModelForm):
    class Meta:
      model = Equipment
      fields = ['equip_name','category', 'condition','place','text','image','stock']
#      widgets = {
#         'name': forms.TextInput(attrs={'placeholder': 'Nickname'}),
#         'text': forms.Textarea(attrs={'placeholder': 'Text', 'rows': 10}),
#      }
      labels = {
         'equip_name':'名前',
         'category': 'カテゴリ',
         'condition': '状態',
         'place': '設置場所',
         'text': '説明',
         'image': '画像',
         'stock': '在庫数',
      }

class StockUpdateForm(forms.ModelForm):
    class Meta:
        model = Equipment
        fields = ['stock']
        labels = {
         'stock': '在庫数',
      }
        

equipment/views.py
from django.shortcuts import render,redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import ListView,CreateView,DetailView,UpdateView,DeleteView
from .models import Equipment,StockChange
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import EquipForm, StockUpdateForm
from order.forms import OrderForm
from order.models import Order



class EquipListView(LoginRequiredMixin, ListView):
    template_name = 'equipment/equip_list.html'
    model = Equipment
    context_object_name = 'equipment'

    def get_queryset(self):
        return Equipment.objects.order_by('-created_at')

class EquipCreateView(LoginRequiredMixin, CreateView):
    template_name = 'equipment/add.html'
    model = Equipment
    form_class = EquipForm  # フォームクラスを指定
    success_url = reverse_lazy('equipment:list')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)
    
class EquipDetailView(LoginRequiredMixin, DetailView):
    model = Equipment
    template_name = 'equipment/detail.html'
    context_object_name = 'equip' #ここの名前でテンプレート上で呼び出す

    def get_context_data(self, **kwargs):#画像がエラーになった時用の回避策
        context = super().get_context_data(**kwargs)
        equip = context['equip']
        context['image_url'] = equip.image.url if equip.image else '/static/images/no_image.jpg'# 画像URLが空の場合、デフォルト画像URLを設定
        context['stock_update_form'] = StockUpdateForm(instance=equip) #在庫数更新のフォームが使えるようになる
        context['stock_changes'] = StockChange.objects.filter(equip=equip).order_by('-changed_date')[:5]
        context['order_form'] = OrderForm() #発注数更新
        context['orders'] = Order.objects.filter(equip=equip).order_by('-order_date')[:5]
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        previous_stock = self.object.stock

        # 在庫数更新フォームの処理
        stock_update_form = StockUpdateForm(request.POST, instance=self.object)
        if stock_update_form.is_valid():
            updated_equip = stock_update_form.save()
            StockChange.objects.create(
                equip=self.object,
                user=request.user,
                previous_stock=previous_stock,
                new_stock=updated_equip.stock,
            )
            return redirect(self.get_success_url())

        # 発注フォームの処理
        order_form = OrderForm(request.POST)
        if order_form.is_valid():
            order = order_form.save(commit=False)
            order.equip = self.object
            order.user = request.user
            order.save()
            return redirect(self.get_success_url())

        # 発注承認処理
        order_id = request.POST.get('approve_order')
        approval_comment = request.POST.get('approval_comment')  # コメントを取得
        if order_id:
            order = get_object_or_404(Order, pk=order_id)
            order.approve(request.user, comment=approval_comment)  # コメントを渡す
            return redirect(self.get_success_url())

        return self.render_to_response(self.get_context_data(
            stock_update_form=stock_update_form,
            order_form=order_form
        ))
    
    def get_success_url(self):
        return reverse_lazy('equipment:detail', kwargs={'pk': self.object.pk})
    

class EquipUpdateView(LoginRequiredMixin, UpdateView):
    model = Equipment
    form_class = EquipForm
    template_name = 'equipment/edit.html'
    
    def get_success_url(self):
        return reverse_lazy('equipment:detail', kwargs={'pk': self.object.pk})

class EquipDeleteView(LoginRequiredMixin, DeleteView):
    model = Equipment
    success_url = reverse_lazy('equipment:list')

templates/equipment/add.html
{% extends "base.html" %}
{% load static %}

{% block title %}備品登録{% endblock title %}

{% block content %}


    <div class="content">
      <div class="content-title">
        <h2>備品登録</h2>
      </div>
      <div class="content-main">

        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
        {% if form.errors %}
        <div class="error">
            <p><font color=red>入力にエラーがあります。もう一度ご確認ください。</font></p>
            {{ form.non_field_errors }}
        </div>
        {% endif %}
        <div class="field">
        {{ form.as_p }}
        </div>
        <div class="button-field">
          <input type="submit" value="登録" class="button">
        </form>
      </div>
      </div>

      
{% endblock content %}

templates/equipment/detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}{{ equip.equip_name }}の詳細{% endblock title %}

{% block content %}
{% comment %} JavaScript {% endcomment %}
<script>
  function confirmDelete() {
    return confirm("本当に削除しますか？この操作は元に戻せません。");
  }
</script>
<script>
  document.addEventListener("DOMContentLoaded", function() {
    const imgElement = document.querySelector("img.image");
    if (imgElement) {
      imgElement.onerror = function() {
        // 画像が破損している場合、画像を非表示にし、no-imageクラスを表示
        imgElement.style.display = "none";
        const noImageDiv = document.createElement("div");
        noImageDiv.className = "no-image";
        noImageDiv.textContent = "NO IMAGE";
        imgElement.parentNode.appendChild(noImageDiv);
      }
    }
  });
  document.addEventListener("DOMContentLoaded", function() {
    const modal = document.getElementById("approvalModal");
    const span = document.getElementsByClassName("close")[0];
    const orderPkInput = document.getElementById("orderPkInput");
  
    document.querySelectorAll(".approve-button").forEach(function(button) {
      button.addEventListener("click", function(event) {
        event.preventDefault();
        const orderPk = button.dataset.orderPk;
        orderPkInput.value = orderPk;
        modal.style.display = "block";
      });
    });
  
    span.onclick = function() {
      modal.style.display = "none";
    }
  
    window.onclick = function(event) {
      if (event.target == modal) {
        modal.style.display = "none";
      }
    }
  });
</script>
{% comment %} JavaScriptここまで {% endcomment %}

    <div class="content">
      <div class="content-title">
        <h2>{{ equip.equip_name }}</h2>
      </div>
      <div class="content-main">

        {% if user.is_admin %}<!-- 管理者の場合にだけ表示される！ -->
          <div class="detail">
            <div class="edit-delete">
              <form action="{% url 'equipment:edit' equip.id %}" method="get">
              {% csrf_token %}
              <input type="submit" class="button" value="編集" class=>
              </form>
              <form action="{% url 'equipment:delete' equip.id %}" method="post" onsubmit="return confirmDelete();">
              {% csrf_token %}
              <input type="submit" class="button" value="削除">
              </form>
          </div>
        {% endif %}

          <div class="detail-content">
            <div class="detail-left">
              {% if equip.image %}<!--もし画像があるときは-->
                <div class="image-box">
                  <img src="{{ equip.image.url }}" alt="NO IMAGE" class="image">
                </div>
              {% else %}<!--もし画像がないときは-->
                <div class="no-image">
                  <p>NO IMAGE</p>
                </div>
              {% endif %}
            </div>
            <div class="detail-right">
              <p class="with-border"> {{ equip.text }}</p>
              <p>カテゴリ　: 　{{ equip.category }}</p>
              <p>状態　　　: 　{{ equip.condition }}</p>
              <p>設置場所　: 　{{ equip.place }}</p>
              <p>在庫数　　:　 {{ equip.stock }}</p>
            </div>
          </div>

        {% if user.is_admin %}<!-- 管理者の場合にだけ表示される！ -->
        <div class="detail">
          
          <h2>在庫数の変更</h2>
            <!-- フォームの表示 -->
            <form method="post">
             {% csrf_token %}
             {{ stock_update_form.as_p }}
             <input type="submit" value="保存" class="button">
            </form>
            
        </div>
        {% endif %}

        <div class="detail">
          <h2>在庫数変更履歴 <span class="small-text">※最新5件を表示</span></h2>
          <table>
            <thead>
              <tr>
                <th>変更日時</th>
                <th>変更前の在庫数</th>
                <th>変更後の在庫数</th>
                <th>変更したユーザー</th>
              </tr>
            </thead>
            <tbody>
              {% for change in stock_changes %}
              <tr>
                <td>{{ change.changed_date }}</td>
                <td>{{ change.previous_stock }}</td>
                <td>{{ change.new_stock }}</td>
                <td>{{ change.user.username }}</td>
              </tr>
              {% empty %}
              <tr>
                <td colspan="4">変更履歴はありません</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>

        <div class="detail">
          <h2>発注依頼</h2>
        <form method="post">
          {% csrf_token %}
          {{ order_form.as_p }}
          <input type="submit" value="発注依頼" class="button">
        </form>
        </div>

        {% if user.is_admin %}
        <div class="detail">
          <h2>発注依頼の承認 <span class="small-text">※最新5件を表示</span></h2>
        <table>
          <tr align="center">
              <th>発注日</th>
              <th>発注者</th>
              <th>発注数</th>
              <th>承認ステータス</th>
              <th>承認コメント</th>
              <th></th>
          </tr>
          {% for order in orders %}
          <tr align="center">
              <td>{{ order.order_date }}</td>
              <td>{{ order.user.username }}</td>
              <td>{{ order.quantity }}</td>
              <td>
                {% if order.approval_status == "承認待ち" %}
                <span style="color: red;"><b>{{ order.approval_status }}</b></span>
                {% elif order.approval_status == "承認済み" %}
                <span style="color: green;"><b>{{ order.approval_status }}</b></span>
                {% else %}
                {{ order.approval_status }}
                {% endif %}
              </td>
              <td>{{ order.comment }}</td>
              <td>
                  {% if order.approval_status != '承認済み' %}
                  <button type="button" class="button approve-button" data-order-pk="{{ order.pk }}">承認する</button>
                  {% else %}
                  
                  {% endif %}
              </td>
          </tr>
          {% empty %}
          <tr>
            <td colspan="5">発注依頼はありません</td>
          </tr>
          {% endfor %}
          {% endif %}
          
      </table>
      </div>


        </div>
      </div>

<!-- モーダルウィンドウ -->
<div id="approvalModal" class="modal">
  <div class="modal-content">
    <span class="close">&times;</span>
  <center>
    <h2>承認コメント</h2>
    <p><small>※コメントしない場合は、無記入で承認するボタンを押してください</small></p>
    <form id="approvalForm" method="post">
      {% csrf_token %}
      <textarea name="approval_comment" rows="7" placeholder="承認に関するコメントを入力してください" style="width:60%;"></textarea>
      <br>
      <br>
      <input type="hidden" id="orderPkInput" name="approve_order">
      <input type="submit" value="承認する" class="button">
    </form>
  </center>
  </div>
</div>

      
{% endblock content %}

templates/equipment/edit.html
{% extends "base.html" %}
{% load static %}

{% block title %}備品編集{% endblock title %}

{% block content %}


    <div class="content">
      <div class="content-title">
        <h2>備品編集</h2>
      </div>
      <div class="content-main">

        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
        {% if form.errors %}
        <div class="error">
            <p><font color=red>入力にエラーがあります。もう一度ご確認ください。</font></p>
            {{ form.non_field_errors }}
        </div>
        {% endif %}
        <div class="field">
        {{ form.as_p }}
        </div>
        <div class="button-field">
          <input type="submit" value="編集" class="button">
        </form>
      </div>
      </div>

      
{% endblock content %}

templates/equipment/equip_list.html
{% extends "base.html" %}
{% load static %}

{% block title %}備品一覧{% endblock title %}

{% block content %}


    <div class="content">
      <div class="content-title">
        <h2>備品一覧</h2>
      </div>
      <div class="content-main">
        <div class="add-button">
        <a href="{% url 'equipment:add' %}">備品を追加</a>
        </div>


        <table>
          <tr align="center">
          <th>名前<small>※クリックで詳細</small></th>
          <th>カテゴリー</th>
          <th>設置場所</th>
          <th>在庫数</th>
          </tr>
          {% for equip in equipment %}
          <tr align="center">
          <td><a href="{% url 'equipment:detail' equip.pk %}">{{ equip.equip_name }}</a> </td>
          <td>{{ equip.category }} </td>
          <td>{{ equip.place }} </td>
          <td>在庫数：{{ equip.stock }}</td>
          </tr>
          {% endfor %}
        </table>

      </div>

      
{% endblock content %}