config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LogoutView

urlpatterns = [
    #path('admin/', admin.site.urls),  # 管理画面を有効化する場合
    path('equipment/', include('equipment.urls')),  # equipment アプリの URL
    path('order_history/', include('order.urls')),  # orderアプリの URL
    path('', include('users.urls')),
    path('logout/', LogoutView.as_view(), name='logout'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

equipment/urls.py
from django.urls import path
from .views import EquipListView,EquipCreateView,EquipDetailView,EquipUpdateView,EquipDeleteView

app_name = 'equipment'
urlpatterns = [
    path('', EquipListView.as_view(), name='list'),
    path('add/', EquipCreateView.as_view(), name='add'),
    path('<int:pk>', EquipDetailView.as_view(), name='detail'),
    path('<int:pk>/edit/', EquipUpdateView.as_view(), name='edit'),
    path('<int:pk>/delete', EquipDeleteView.as_view(), name='delete'),
]

order/urls.py
from django.urls import path
from .views import OrderListView

app_name = 'order'
urlpatterns = [
    path('', OrderListView.as_view(), name='history'),
]

users/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView,LogoutView
from .views import CustomUserListView,IndexView,SignUpView,UserUpdateView




app_name = "users"
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('users/', CustomUserListView.as_view(), name='users'),
    path('users/<int:pk>/edit/', UserUpdateView.as_view(), name='edit'),
    path('register/', SignUpView.as_view(), name='register'),
    path('login/', LoginView.as_view(template_name='users/sign_in.html'), name='login'),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title> {% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <header>
        <div class="nav-bar">
            <div class="nav-left">
                <ul>
                    {% if user.is_authenticated %} <!--ログインしているときの表示-->
                    <li><a href="{% url 'equipment:list' %}">備品一覧</a></li>
                    <li><a href="{% url 'order:history' %}">発注履歴</a></li>
                    {% else %}<!--ログインしてないときの表示-->
                    <li><a href="{% url 'users:index' %}">ホーム</a></li>
                    {% endif %}
                </ul>
            </div>

            <div class="nav-center">
                <p><font color=pink size=10px><b>※西澤手元開発用</b></font></p>


            </div>

            <div class="nav-right">
                <ul>
                    {% if user.is_authenticated %} <!--ログインしているときの表示-->
                    {% if user.is_authenticated %}
                    <li>ようこそ、 {{user.username}}さん
                        {% if user.is_admin %}<!--ログインユーザーが管理者のときだけ表示-->
                        (管理者)
                        {% endif %}
                    </li>
                    {% endif %}
                        {% if user.is_admin %}<!--ログインユーザーが管理者のときだけ表示-->
                        <li><a href="{% url 'users:users' %}">ユーザー一覧</a></li>
                        {% endif %}
                    <li><a href="{% url 'logout' %}">ログアウト</a></li>
                    {% else %}<!--ログインしてないときの表示-->
                    <li><a href="{% url 'users:register' %}">新規登録</a></li>
                    <li><a href="{% url 'users:login' %}">ログイン</a></li>
                    {% endif %}
                </ul>
            </div>
          </div>
    </header>

    {% block content %}{% endblock content %}

  </body>
  </html>