config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LogoutView

urlpatterns = [
    #path('admin/', admin.site.urls),  # 管理画面を有効化する場合
    path('equipment/', include('equipment.urls')),  # equipment アプリの URL
    path('order_history/', include('order.urls')),  # orderアプリの URL
    path('', include('users.urls')),
    path('logout/', LogoutView.as_view(), name='logout'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path
from .views import OrderListView

app_name = 'order'
urlpatterns = [
    path('', OrderListView.as_view(), name='history'),
]

users/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView,LogoutView
from .views import CustomUserListView,IndexView,SignUpView,UserUpdateView




app_name = "users"
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('users/', CustomUserListView.as_view(), name='users'),
    path('users/<int:pk>/edit/', UserUpdateView.as_view(), name='edit'),
    path('register/', SignUpView.as_view(), name='register'),
    path('login/', LoginView.as_view(template_name='users/sign_in.html'), name='login'),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin

# カスタム ユーザーマネージャー
class CustomUserManager(BaseUserManager):
    def create_user(self, email, username, password=None, **extra_fields):
        if not email:
            raise ValueError('Email address is required')
        email = self.normalize_email(email)
        user = self.model(email=email, username=username, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user


# カスタム ユーザーモデル
class CustomUser(AbstractBaseUser, PermissionsMixin):

    username = models.CharField(unique=True, max_length=50, null=False)
    email = models.EmailField(unique=True, null=False)

    is_staff = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    registration_date = models.DateTimeField(auto_now_add=True)

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']
    

    objects = CustomUserManager()


    def __str__(self):
        return self.email

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm,UserChangeForm
from django.contrib.auth import get_user_model

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()  # カスタムユーザーモデルを取得
        fields = ('email', 'username','is_staff','is_admin') 
        labels = {
         'username':'ユーザー名',
         'email': 'email',
         'is_staff': 'スタッフとして登録する',
         'is_admin': '管理者として登録する',
      }

class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ('email', 'username', 'is_staff', 'is_admin')
        labels = {
            'username': 'ユーザー名',
            'email': 'email',
            'is_staff': 'スタッフとして登録する',
            'is_admin': '管理者として登録する',
        }

    def clean_username(self):
        username = self.cleaned_data.get('username')
        if get_user_model().objects.filter(username=username).exclude(pk=self.instance.pk).exists():
            raise forms.ValidationError('このユーザー名は既に使用されています。')
        return username

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if get_user_model().objects.filter(email=email).exclude(pk=self.instance.pk).exists():
            raise forms.ValidationError('このメールアドレスは既に使用されています。')
        return email

users/views.py
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404
from django.views import generic
from .forms import CustomUserCreationForm,CustomUserChangeForm
from django.views.generic import ListView,TemplateView,UpdateView
from .models import CustomUser
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseForbidden


class IndexView(TemplateView):
    template_name = 'users/index.html'

class UserUpdateView(LoginRequiredMixin, UpdateView):
    model = CustomUser
    form_class = CustomUserChangeForm
    template_name = 'users/edit.html'
    success_url = reverse_lazy('users:users')

    def get_object(self, queryset=None):
        # URL から渡された pk を使って、特定のユーザーを取得
        user_id = self.kwargs.get("pk")
        return get_object_or_404(CustomUser, pk=user_id)

class SignUpView(generic.CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('equipment:list')  # 登録完了後にリダイレクトするURL
    template_name = 'users/sign_up.html'

class CustomUserListView(LoginRequiredMixin,ListView):
    template_name = 'users/users.html'
    model = CustomUser
    context_object_name = 'users'

    def get_queryset(self):
        return CustomUser.objects.order_by('-registration_date')
    
    def dispatch(self, request, *args, **kwargs):#管理者以外にユーザー一覧へのアクセスを許可しない
        # ログインユーザーのis_adminがTrueかどうかをチェック
        if not request.user.is_admin:
            return HttpResponseForbidden("このページにアクセスする権限がありません。")
        return super().dispatch(request, *args, **kwargs)

templates/users/edit.html
{% extends "base.html" %}
{% load static %}

{% block title %}ユーザー情報の編集{% endblock title %}

{% block content %}
    <div class="content">
      <div class="content-title">
        <h2>ユーザー情報の編集</h2>
      </div>
      <div class="content-main">
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {% if form.errors %}
            <div class="error">
                <p><font color="red">入力にエラーがあります。もう一度ご確認ください。</font></p>
                {{ form.non_field_errors }}
            </div>
          {% endif %}
          <div class="field">
              {{ form.username.label_tag }}
              {{ form.username }}
              {% if form.username.errors %}
                <ul class="errorlist">
                  {% for error in form.username.errors %}
                    <li><font color="red">{{ error }}</font></li>
                  {% endfor %}
                </ul>
              {% endif %}
          </div>
          <div class="field">
              {{ form.email.label_tag }}
              {{ form.email }}
              {% if form.email.errors %}
                <ul class="errorlist">
                  {% for error in form.email.errors %}
                    <li><font color="red">{{ error }}</font></li>
                  {% endfor %}
                </ul>
              {% endif %}
          </div>
          <div class="field">
              {{ form.is_staff.label_tag }}
              {{ form.is_staff }}
          </div>
          <div class="field">
              {{ form.is_admin.label_tag }}
              {{ form.is_admin }}
          </div>
          <div class="button-field">
              <input type="submit" value="保存" class="button">
          </div>
        </form>
      </div>
    </div>
{% endblock content %}

templates/users/index.html
{% extends "base.html" %}
{% load static %}

{% block title %}トップページ{% endblock title %}

{% block content %}

<div class="content">
      <div class="content-title">
        <h2>備品管理システムへようこそ</h2>
      </div>
      <div class="content-main">
        <p><a href="{% url 'users:login' %}">ログイン</a> または <a href="{% url 'users:register' %}">登録</a> して備品を管理しましょう。</p>
      </div>
</div>

{% endblock content %}

templates/users/sign_in.html
{% extends "base.html" %}
{% load static %}

{% block title %}ログイン{% endblock title %}

{% block content %}


    <div class="content">
      <div class="content-title">
        <h2>ログイン</h2>
      </div><!--content-titleのとじ-->

      <div class="content-main">

        <form method="post">
          {% csrf_token %}
        <div class="login-form">

          {% if form.non_field_errors %}
          <ul class="errorlist">
            {% for error in form.non_field_errors %}
              <li><font color=red>{{ error }}</font></li>
            {% endfor %}
          </ul>
          {% endif %}

          <div class="login-name">
          ユーザー名:
          {{ form.username }}
          {% if form.username.errors %}
          <ul class="errorlist">
          {% for error in form.username.errors %}
               <li>{{ error }}</li>
          {% endfor %}
          </ul>
          {% endif %}
          </div><!--login-nameのとじ-->
          <div class="login-pass">
        パスワード:
        {{ form.password }}
        {% if form.password.errors %}
        <ul class="errorlist">
            {% for error in form.password.errors %}
                <li>{{ error }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        </div><!--login-passのとじ-->
        <div class="button-field">
          <input type="submit" value="ログイン" class="button">
        </div><!--buttonのとじ-->
      </form>

      </div><!--login-formのとじ-->
      <p>アカウントをお持ちでないですか？登録は<a href="{% url 'users:register' %}">こちら.</a></p>
      
      </div><!--content-mainのとじ-->

    </div><!--contentのとじ-->

{% endblock content %}

templates/users/sign_up.html
{% extends "base.html" %}
{% load static %}

{% block title %}新規登録{% endblock title %}

{% block content %}

    <div class="content">
      <div class="content-title">
        <h2>新規登録</h2>
      </div>
      <div class="content-main">

        <form method="post">
          {% csrf_token %}
        {% if form.errors %}
        <div class="error">
            <p><font color=red>入力にエラーがあります。もう一度ご確認ください。</font></p>
            {{ form.non_field_errors }}
        </div>
        {% endif %}
        <div class="field">
            {{ form.username.label_tag }}
            {{ form.username }}
            {% if form.username.errors %}
            <ul class="errorlist">
                {% for error in form.username.errors %}
                    <li><font color=red>{{ error }}</font></li>
                {% endfor %}
            </ul>
            {% endif %}
        </div>

        <div class="field">
            {{ form.email.label_tag  }}
            {{ form.email }}
            {% if form.email.errors %}
            <ul class="errorlist">
                {% for error in form.email.errors %}
                    <li><font color=red>{{ error }}</font></li>
                {% endfor %}
            </ul>
            {% endif %}
        </div>

        <div class="field">
            {{ form.password1.label_tag  }}<small>(英数字含む8文字以上)</small>
            {{ form.password1 }}
            {% if form.password1.errors %}
            <ul class="errorlist">
                {% for error in form.password1.errors %}
                    <li><font color=red>{{ error }}</font></li>
                {% endfor %}
            </ul>
            {% endif %}
        </div>

        <div class="field">
            {{ form.password2.label_tag  }}
            {{ form.password2 }}
            {% if form.password2.errors %}
            <ul class="errorlist">
                {% for error in form.password2.errors %}
                    <li><font color=red>{{ error }}</font></li>
                {% endfor %}
            </ul>
            {% endif %}
        </div>
        <div class="field">
            {{ form.is_staff.label_tag  }}
            {{ form.is_staff }}
        </div>
        <div class="field">
            {{ form.is_admin.label_tag  }}
            {{ form.is_admin }}
        </div>


        <div class="button-field">
            <input type="submit" value="登録" class="button">
        </div>
      </div>
    </form>
    </div>

{% endblock content %}

templates/users/users.html
{% extends "base.html" %}
{% load static %}

{% block title %}ユーザー一覧{% endblock title %}

{% block content %}


    <div class="content">
      <div class="content-title">
        <h2>ユーザー一覧</h2>
      </div>
      <div class="content-main">

        <table cellspacing="10" cellpadding="10">
          <tr align="center">
          <th>ユーザー名</th>
          <th>メールアドレス</th>
          <th>スタッフ</th>
          <th>管理者</th>
          <th>操作</th>
          </tr>
          {% for user in users %}
          <tr align="center">
          <td>{{ user.username }} </td>
          <td>{{ user.email }} </td>
          <td>{{ user.is_staff }} </td>
          <td>{{ user.is_admin }}</td>
          <td><a href="{% url 'users:edit' user.id %}">編集</a></td>
          </tr>
          {% endfor %}
        </table>

      </div>

      
{% endblock content %}