config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LogoutView

urlpatterns = [
    #path('admin/', admin.site.urls),  # 管理画面を有効化する場合
    path('equipment/', include('equipment.urls')),  # equipment アプリの URL
    path('order_history/', include('order.urls')),  # orderアプリの URL
    path('', include('users.urls')),
    path('logout/', LogoutView.as_view(), name='logout'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

equipment/urls.py
from django.urls import path
from .views import EquipListView,EquipCreateView,EquipDetailView,EquipUpdateView,EquipDeleteView

app_name = 'equipment'
urlpatterns = [
    path('', EquipListView.as_view(), name='list'),
    path('add/', EquipCreateView.as_view(), name='add'),
    path('<int:pk>', EquipDetailView.as_view(), name='detail'),
    path('<int:pk>/edit/', EquipUpdateView.as_view(), name='edit'),
    path('<int:pk>/delete', EquipDeleteView.as_view(), name='delete'),
]

order/urls.py
from django.urls import path
from .views import OrderListView

app_name = 'order'
urlpatterns = [
    path('', OrderListView.as_view(), name='history'),
]

order/models.py
from django.db import models
from django.conf import settings
from equipment.models import Equipment
from django.utils import timezone

class Order(models.Model):
  class Meta:
    db_table = 'order'

  equip = models.ForeignKey(Equipment, on_delete=models.CASCADE)
  user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='orders')
  quantity = models.PositiveIntegerField()
  order_date = models.DateTimeField(auto_now_add=True)
  approval_status = models.CharField(max_length=50, default='承認待ち')
  approval_date = models.DateTimeField(null=True, blank=True)
  approval_user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='approved_orders', null=True, blank=True)
  comment = models.TextField(null=True, blank=True)

  def approve(self, user, comment=None):
      self.approval_status = '承認済み'
      self.approval_date = timezone.now()
      self.approval_user = user  # 承認したユーザーを記録
      self.comment = comment  # コメントを保存
      self.save()

order/forms.py
from .models import Order
from django import forms

class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['quantity']
        labels = {
         'quantity': '発注数',
      }
        
class OrderApprovalForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = []  # フォームのフィールドは空にします。POSTリクエストでフォームが提出されたときに、`approve` メソッドを呼び出します。

order/views.py
from django.shortcuts import render
from django.views.generic import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Order

# Create your views here.
class OrderListView(LoginRequiredMixin, ListView):
    template_name = 'order/history.html'
    model = Order
    context_object_name = 'orders'
    paginate_by = 5  # 1ページに表示する発注数

    def get_queryset(self):
        # すべての注文を取得し、発注日の降順に並べ替える
        queryset = Order.objects.order_by('-order_date')
        
        # GETパラメータからフィルタリングのステータスを取得
        status_filter = self.request.GET.get('status_filter')
        
        # フィルタリングが選択されている場合は、クエリセットをフィルタリング
        if status_filter:
            queryset = queryset.filter(approval_status=status_filter)
        
        return queryset

templates/order/history.html
{% extends "base.html" %}
{% load static %}

{% block title %}発注履歴{% endblock title %}

{% block content %}


    <div class="content">
      <div class="content-title">
        <h2>発注履歴</h2>
      </div>
      <div class="content-main">


        <form method="get" action="">
          <label for="status_filter"><b>フィルター：条件を選択してください▶</b></label>
          <select name="status_filter" id="status_filter" onchange="this.form.submit()">
            <option value="">全て</option>
            <option value="承認待ち" {% if request.GET.status_filter == "承認待ち" %}selected{% endif %}>承認待ち</option>
            <option value="承認済み" {% if request.GET.status_filter == "承認済み" %}selected{% endif %}>承認済み</option>
            <!-- 必要に応じて他のステータスも追加 -->
          </select>
        </form>


    <!-- 件数表示 -->
    <div class="item-count">
      全{{ page_obj.paginator.count }}件中
      {{ page_obj.start_index }}件目から{{ page_obj.end_index }}件目を表示中
    </div>

    <!-- ページネーションリンク -->
    <div class="pagination">
      <span class="step-links">
        {% if page_obj.has_previous %}
        <a href="?{% if request.GET.status_filter %}status_filter={{ request.GET.status_filter }}&{% endif %}page=1">&laquo; 最初</a>
        <a href="?{% if request.GET.status_filter %}status_filter={{ request.GET.status_filter }}&{% endif %}page={{ page_obj.previous_page_number }}">前のページ</a>
      {% else %}
        <span class="disabled">&laquo; 最初</span>
        <span class="disabled">前のページ</span>
      {% endif %}
  
      {% if page_obj.has_next %}
        <a href="?{% if request.GET.status_filter %}status_filter={{ request.GET.status_filter }}&{% endif %}page={{ page_obj.next_page_number }}">次のページ</a>
        <a href="?{% if request.GET.status_filter %}status_filter={{ request.GET.status_filter }}&{% endif %}page={{ page_obj.paginator.num_pages }}">最後 &raquo;</a>
      {% else %}
        <span class="disabled">次のページ</span>
        <span class="disabled">最後 &raquo;</span>
      {% endif %}
      </span>
    </div>


        <table cellspacing="10" cellpadding="10">
          <tr align="center">
          <th>発注日</th>
          <th>備品名</th>
          <th>数量</th>
          <th>ステータス</th>
          <th>承認コメント</th>
          <th>承認者</th>
          </tr>
          {% for order in orders %}
          <tr align="center">
          <td>{{ order.order_date }}</a> </td>
          <td><a href="{% url 'equipment:detail' order.equip.pk %}">{{ order.equip.equip_name }}</a> </td>
          <td>{{ order.quantity }} </td>
          <td>
            {% if order.approval_status == "承認待ち" %}
            <span style="color: red;"><b>{{ order.approval_status }}</b></span>
            {% elif order.approval_status == "承認済み" %}
            <span style="color: green;"><b>{{ order.approval_status }}</b></span>
            {% else %}
            {{ order.approval_status }}
            {% endif %}
          </td>
          <td>
            {% if order.approval_status == "承認待ち" %}
            <span>－</span>
            {% elif order.approval_status == "承認済み" %}
            <span>{{ order.comment }}</span>
            {% else %}
            <span>－</span>
            {% endif %}
          </td>
          <td>
            {% if order.approval_status == "承認待ち" %}
            <span>－</span>
            {% elif order.approval_status == "承認済み" %}
            {{ order.approval_user.username }}
            {% else %}
            <span>－</span>
            {% endif %}
          </td>
          </tr>
          {% empty %}
          <tr>
            <td colspan="5">発注履歴はありません</td>
          </tr>
          {% endfor %}
        </table>

      </div>

      
{% endblock content %}